// Generate a table of sinewave constants for use in C/C++.
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println("// Generated by gensine.go: [0,90) degrees, 256 steps, 16-bit")
	fmt.Println("static uint16_t sineTable [256] = {")
	line := "    "
	for i := 0; i < 256; i++ {
		v := math.Sin(float64(i) * math.Pi / 512)
		s := fmt.Sprint(math.Floor(v*(1<<15) + 0.5))
		if len(line)+len(s) > 79 {
			fmt.Println(line)
			line = "    "
		}
		line += s + ","
	}
	fmt.Println(line)
	fmt.Println("};")
}
