all:
	srec_cat -Output usb-generic.bin -Binary usb-generic.hex -Intel
	srec_cat -Output usb-hytiny.bin -Binary usb-hytiny.hex -Intel
	srec_cat -Output usb-olimexino.bin -Binary usb-olimexino.hex -Intel
